### ISSUE TITLE
Typo in blog post?

### ISSUE THREAD

**Issue by 99991** [avik-das/scheme-compiler#1]
Thank you for [this article](https://scratchpad.avikdas.com/elf-explanation/elf-explanation.html)! I found it very educational.

I think there is a typo in the program header table offset (third row in the blog post). The offset should probably be `c0 00 00 00 00 00 00 00` instead of `00 01 00 00 00 00 00 00`.

![program_header_table](https://github.com/avik-das/garlic/assets/18725165/04bb2200-8a99-4662-9ef8-f066a70c1d65)

For comparison, here are the two different bytes in your code: https://github.com/avik-das/garlic/blob/master/recursive/elf-exploration/write-elf.rb#L29C7-L29C17

**Comment by avik-das** [comment]
Thanks for the kind words @99991.

You're 100% right, that was a typo. I fixed it in the [source code](https://git.avikdas.com/avik/elf-explanation/commit/24dd3fce4c61804d18fd2b74236350ac5399d818), attributed you, and deployed the changes. Thanks for reporting!
